export {default} from './HomePage';
export * from './MenuPage';
export * from './EventsPage';
export * from './Reservation/ReservePage';
export * from './FeedbacksPage';
export * from './GalleryPage';
export * from './GalleryDetailsPage';
export * from './ContactsPage';
export * from './NotFoundPage';
