export {HomePage} from './HomePage';
export {MenuPage} from './MenuPage';
export {EventsPage} from './EventsPage';
export {ReservePage} from './Reservation/ReservePage';
export {FeedbacksPage} from './FeedbacksPage';
export {GalleryPage} from './GalleryPage';
export {GalleryDetailsPage} from './GalleryDetailsPage';
export {ContactsPage} from './ContactsPage';
export {NotFoundPage} from './NotFoundPage';